#!/usr/bin/env node
// Builds the GitHub Pages site in docs/ from the single-file app in src/app.html.
//
// src/app.html is a page *fragment* (title, styles, markup, script — no <html>/<head>),
// the same file that is published as a claude.ai artifact. This script wraps it in a
// full document and adds what a standalone install needs: a web app manifest, a service
// worker for offline use, and the home-screen icons.
//
// Usage: node scripts/build.js

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'src', 'app.html');
const ICONS = path.join(ROOT, 'assets', 'icons');
const OUT = path.join(ROOT, 'docs');

const THEME = '#2F55E4';
const BACKGROUND = '#EFF2EC';
const DESCRIPTION = 'Her gün, her hafta ya da her ay tekrar eden görevler ve ilaç takibi.';

const src = fs.readFileSync(SRC, 'utf8');
const cut = src.indexOf('</style>') + '</style>'.length;
const headPart = src.slice(0, cut);
const bodyPart = src.slice(cut);

const index = `<!doctype html>
<html lang="tr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="description" content="${DESCRIPTION}">
<meta name="theme-color" content="${THEME}">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Ritim">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
<link rel="manifest" href="manifest.webmanifest">
<link rel="icon" type="image/png" sizes="192x192" href="icons/icon-192.png">
<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">
<style>
:root{padding-top:env(safe-area-inset-top,0px);padding-bottom:env(safe-area-inset-bottom,0px)}
img{max-width:100%}
[hidden]{display:none!important}
</style>
${headPart}
</head>
<body>
${bodyPart}
</body>
</html>
`;

const version = crypto.createHash('sha1').update(index).digest('hex').slice(0, 10);

const manifest = {
  name: 'Ritim – Görev ve İlaç Takibi',
  short_name: 'Ritim',
  description: DESCRIPTION,
  lang: 'tr',
  start_url: './',
  scope: './',
  display: 'standalone',
  orientation: 'portrait',
  background_color: BACKGROUND,
  theme_color: THEME,
  icons: [
    { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png' },
    { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    { src: 'icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
};

const sw = `// Ritim service worker — keeps the app usable offline. Generated by scripts/build.js.
const CACHE = 'ritim-${version}';
const CORE = ['./', './index.html', './manifest.webmanifest', './icons/icon-192.png', './icons/icon-512.png'];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(CORE)));
  self.skipWaiting();
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))));
  self.clients.claim();
});
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // Account and sync requests must always reach the server.
  if (url.pathname.includes('/api/')) return;
  // The page itself: network first so updates arrive, cache when offline.
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).then(r => {
      const copy = r.clone(); caches.open(CACHE).then(c => c.put('./index.html', copy)); return r;
    }).catch(() => caches.match('./index.html')));
    return;
  }
  const cacheable = url.origin === location.origin || url.hostname.endsWith('fonts.googleapis.com') || url.hostname.endsWith('fonts.gstatic.com');
  if (!cacheable) return;
  e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(r => {
    if (r.ok || r.type === 'opaque') { const copy = r.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return r;
  })));
});
self.addEventListener('notificationclick', e => {
  e.notification.close();
  e.waitUntil(self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(cs => cs.length ? cs[0].focus() : self.clients.openWindow('./')));
});
`;

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(path.join(OUT, 'icons'), { recursive: true });
fs.writeFileSync(path.join(OUT, 'index.html'), index);
fs.writeFileSync(path.join(OUT, 'manifest.webmanifest'), JSON.stringify(manifest, null, 2));
fs.writeFileSync(path.join(OUT, 'sw.js'), sw);
for (const f of fs.readdirSync(ICONS)) fs.copyFileSync(path.join(ICONS, f), path.join(OUT, 'icons', f));

console.log(`docs/ built (version ${version})`);
